server:
  port: 8080
  tomcat: 
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto
    max-threads: 1000
    min-spare-threads: 30
    
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.254:3306/testdb?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Hongkong
    username: root
    password: root
    
  aop:
    proxy-target-class: true
  servlet:
     multipart:
        max-file-size: 10MB
        max-request-size: 100MB
        
  devtools:
    restart:
      enabled: true

  #REDIS (RedisProperties)
  redis: 
    #Redis数据库索引（默认为0）
    database: 0
    #Redis服务器地址
    host: 192.168.0.254
    #Redis服务器连接端口
    port: 6379
    #Redis服务器连接密码（默认为空）
    password: Credit2016Admin
    pool:
      #连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      #连接池中的最大空闲连接
      max-idle: 8
      #连接池中的最小空闲连接
      min-idle: 0
      #连接超时时间（毫秒）
      timeout: 0

  #DUBBO配置
  dubbo:
    application:
      name: testrabbitmq-web
      id: testrabbitmq-web
    server: true
    registry:
      address: zookeeper://192.168.0.254:2181
    protocol:
      name: dubbo
      port: 20880

  rabbitmq: 
    host: 192.168.0.254
    port: 5672
    username: qq
    password: 1234
    virtual-host: /qq
    publisher-confirms: true
    publisher-returns: true
    connection-timeout: 1000
    
  #定时任务
  schedule:
    #是否开启
    isOpen: true

#是否开启swagger文档    
swagger:
  enable: true 
  
#日志
logging:
  level.root: info
  level.com.gxzx: info
  #配置日志文件路径，支持相对和绝对路径
  path: c:/testrabbitmq-web-logs/
  file: testrabbitmq-web.log

#MyBatis
mybatis-plus:                   
  mapper-locations: classpath:com/gxzx/testrabbitmq/web/mapper/xml/*Mapper.xml

  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.gxzx.testrabbitmq.web.entity
  #typeEnumsPackage: com.gxzx.testrabbitmq.web.entity.enums
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    #logic-delete-value: 0
    #logic-not-delete-value: 1
    #自定义填充策略接口实现
    #meta-object-handler: com.gxzx.otc.web.config.mybatis.OtcMetaObjectHandler
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    #打印预处理格式的sql语句，调试用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #打印带有执行时间的性能分析SQL，调试用
    log-performance: true

#工程全局参数
project-properties: 
  #系统参数
  sys-properties:
    snowflakeIdWorker: 
      #数据中心ID(0~31)
      dataCenterId: 0 
      #工作机器ID(0~31)
      workMachineId: 1 
  #业务参数
  biz-properties: 
    #间隔时间（单位:毫秒）
    minRequestIntervalTime: 1000
    #请求间隔周期时间（单位:次数）
    maxMaliciousTimes: 5
    #otc顶级域名
    first-class-domain-name: cpct-otc.pro
    #运维全局秘钥
    operation-secret: otcSeccret
    #tokenName
    tokenName: accessToken

    